version: 2

jobs:
  test:
    working_directory: ~/notes

    docker:
      - image: node:12

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-{{ .Branch }}
            - v1-master-{{ checksum "yarn.lock" }}
            - v1-master

      - run:
          name: Install dependencies
          command: yarn

      - run:
          name: Run tests
          command: yarn test

      - save_cache:
          key: v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.config/yarn
            - ~/.yarn
            - ~/notes/node_modules

workflows:
  version: 2
  stack:
    jobs:
      - test
